name: Review BCR Pull Requests
on:
  schedule:
    - cron: "*/10 * * * *" # Run this action every 10 mins
  workflow_dispatch:       # So that this can be triggered manually

jobs:
  review_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        if: github.repository_owner == 'bazelbuild'
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Run BCR PR Reviewer
        if: github.repository_owner == 'bazelbuild'
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@102c2a75b67cf28b1a7e5959a6b7f06d8f4a92a6 # master
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: review_prs
