name: Review BCR Pull Requests
on:
  schedule:
    - cron: "*/10 * * * *" # Run this action every 10 mins
  workflow_dispatch:       # So that this can be triggered manually

jobs:
  review_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        if: github.repository_owner == 'bazelbuild'
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Run BCR PR Reviewer
        if: github.repository_owner == 'bazelbuild'
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@95799f710e6e18024b00c8a075747bd8a14d1337 # master
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: review_prs
